name: Build & Publish ICS

on:
  schedule:
    - cron: '*/5 * * * *' # каждые 6 часов
  workflow_dispatch: {} # возможность запустить вручную

permissions:
  contents: write # нужно для коммита events.ics

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Устанавливаем системные зависимости браузера через официальный action,
      # иначе Playwright headless может не стартовать в CI
      - name: Install Playwright browser dependencies
        uses: microsoft/playwright-github-action@v1
        with:
          version: 1.47.0

      - name: Install Chromium for Playwright (Python)
        run: |
          python -m playwright install chromium

      - name: Build events.ics
        env:
          HEADFUL: '0' # строго headless в CI
          RUDA_URL: 'https://rudagames.com/helsinki'
          ICS_PATH: 'events.ics'
          CLICK_LIMIT: '30'
          WAIT_AFTER_CLICK_MS: '900'
          NAV_TIMEOUT_MS: '90000'
          DEBUG_HTML: '0' # выключим page.debug.html в CI
        run: |
          python rudagames_to_ics_playwright.py
          test -s events.ics || { echo "events.ics is empty!"; exit 1; }

      - name: Commit updated events.ics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add events.ics
          git diff --staged --quiet && echo "No changes to commit" || git commit -m "Update events.ics"
          git push
